import streamlit as st


_FALLBACK_CHATBOT_DISCLAIMER = (
    "This tutoring response was generated by an AI system. It may reflect biases present "
    "in its training data or prompt design. If you notice language that seems biased, "
    "condescending, or inappropriate, please report it so we can improve."
)


def render_chatbot_bias_banners(audit_result):
    """Show ethical disclaimer and any bias warnings from the chatbot bias audit."""
    if not audit_result:
        return

    # Overall risk warning
    risk = audit_result.get("overall_bias_risk", "low")
    if risk in ("medium", "high"):
        flagged = audit_result.get("flagged_message_count", 0)
        audited = audit_result.get("audited_message_count", 0)
        severity_label = "Moderate" if risk == "medium" else "High"
        st.warning(
            f"{severity_label} bias risk detected: {flagged} of {audited} messages flagged. "
            f"Review the details below."
        )

    # Bias flags details
    bias_flags = audit_result.get("bias_flags", [])
    deterministic_flags = audit_result.get("deterministic_flags", [])

    if bias_flags or deterministic_flags:
        with st.expander("View chatbot bias audit details"):
            if bias_flags:
                st.markdown("**Chatbot Bias Flags**")
                for flag in bias_flags:
                    severity = flag.get("severity", "low")
                    icon = {"low": "🟡", "medium": "🟠", "high": "🔴"}.get(severity, "🟡")
                    st.markdown(
                        f"{icon} **Message {flag.get('message_index', 0)}** — "
                        f"*{flag.get('bias_category', '')}* ({severity})\n\n"
                        f"  {flag.get('explanation', '')}\n\n"
                        f"  **Suggestion:** {flag.get('suggestion', '')}"
                    )

            if deterministic_flags:
                st.markdown("**Language & Tone Warnings**")
                for flag in deterministic_flags:
                    st.markdown(
                        f"⚠️ {flag.get('explanation', '')}  \n"
                        f"**Suggestion:** {flag.get('suggestion', '')}"
                    )
