import streamlit as st


_FALLBACK_CONTENT_DISCLAIMER = (
    "This learning content was generated by an AI system. It may reflect biases present "
    "in its training data or source materials. If you notice content that seems biased, "
    "culturally insensitive, or inappropriate, please report it so we can improve."
)


def render_content_bias_banners(goal):
    """Show ethical disclaimer and any bias warnings from the content bias audit."""
    audit = goal.get("content_bias_audit")

    # Always show ethical disclaimer (even if audit failed)
    disclaimer = (audit or {}).get("ethical_disclaimer", _FALLBACK_CONTENT_DISCLAIMER)
    st.info(disclaimer)

    if not audit:
        return

    # Overall risk warning
    risk = audit.get("overall_bias_risk", "low")
    if risk in ("medium", "high"):
        flagged = audit.get("flagged_section_count", 0)
        audited = audit.get("audited_section_count", 0)
        severity_label = "Moderate" if risk == "medium" else "High"
        st.warning(
            f"{severity_label} content bias risk detected: {flagged} of {audited} sections flagged. "
            f"Review the details below."
        )

    # Bias flags details
    bias_flags = audit.get("bias_flags", [])
    deterministic_flags = audit.get("deterministic_flags", [])

    if bias_flags or deterministic_flags:
        with st.expander("View content bias audit details"):
            if bias_flags:
                st.markdown("**Content Bias Flags**")
                for flag in bias_flags:
                    severity = flag.get("severity", "low")
                    icon = {"low": "🟡", "medium": "🟠", "high": "🔴"}.get(severity, "🟡")
                    st.markdown(
                        f"{icon} **{flag.get('section_title', 'Unknown')}** — "
                        f"*{flag.get('bias_category', '')}* ({severity})\n\n"
                        f"  {flag.get('explanation', '')}\n\n"
                        f"  **Suggestion:** {flag.get('suggestion', '')}"
                    )

            if deterministic_flags:
                st.markdown("**Language Bias Warnings**")
                for flag in deterministic_flags:
                    st.markdown(
                        f"⚠️ {flag.get('explanation', '')}  \n"
                        f"**Suggestion:** {flag.get('suggestion', '')}"
                    )
