import streamlit as st
from utils.request_api import (
    create_learner_profile,
    get_learner_profile,
    update_learning_preferences,
    update_learner_information,
    auth_delete_user,
    get_app_config,
    get_behavioral_metrics,
    delete_user_data,
)
from components.skill_info import render_skill_info
from utils.pdf import extract_text_from_pdf
from utils.state import (
    delete_persistent_state,
    get_selected_goal,
    save_persistent_state,
    propagate_profile_fields_to_other_goals,
)


def render_learner_profile():
    # Title and introduction
    goal = get_selected_goal()
    if not isinstance(goal, dict):
        st.info("No active goal selected.")
        return

    st.title("Learner Profile")
    st.write("An overview of the learner's background, goals, progress, preferences, and behavioral patterns.")
    if not goal["learner_profile"]:
        with st.spinner('Identifying Skill Gap ...'):
            st.info("Please complete the onboarding process to view the learner profile.")
    else:
        try:
            render_learner_profile_info(goal)
        except Exception as e:
            st.error("An error occurred while rendering the learner profile.")
            # Try to retrieve the existing stored profile first to avoid overwriting FSLSM/mastery data.
            # Only create a new one if the backend has no record for this goal.
            with st.spinner("Re-prepare your profile ..."):
                user_id = st.session_state.get("userId")
                goal_id = st.session_state.get("selected_goal_id")
                learner_profile = None
                if user_id is not None and goal_id is not None:
                    learner_profile = get_learner_profile(user_id, goal_id)
                if learner_profile is None:
                    learner_profile = create_learner_profile(
                        goal["learning_goal"],
                        st.session_state["learner_information"],
                        goal["skill_gaps"],
                        user_id=user_id,
                        goal_id=goal_id,
                    )
            goal["learner_profile"] = learner_profile
            try:
                save_persistent_state()
            except Exception:
                pass
            st.rerun()

_FALLBACK_PROFILE_DISCLAIMER = (
    "This learner profile was generated by AI based on limited information. "
    "Learning style preferences and proficiency levels are estimates and may not "
    "fully represent your actual preferences or abilities."
)


def render_fairness_banners(goal):
    """Show ethical disclaimer and any fairness warnings from the validation."""
    fairness = goal.get("profile_fairness")

    # Always show ethical disclaimer (even if validation failed)
    disclaimer = (fairness or {}).get("ethical_disclaimer", _FALLBACK_PROFILE_DISCLAIMER)
    st.info(disclaimer)

    if not fairness:
        return

    # Overall risk warning
    risk = fairness.get("overall_fairness_risk", "low")
    if risk in ("medium", "high"):
        flagged = fairness.get("flagged_fields_count", 0)
        checked = fairness.get("checked_fields_count", 0)
        severity_label = "Moderate" if risk == "medium" else "High"
        st.warning(
            f"{severity_label} fairness risk detected: {flagged} of {checked} fields flagged. "
            f"Review the details below and consider adjusting the profile."
        )

    # Fairness flags details
    fairness_flags = fairness.get("fairness_flags", [])
    deviation_flags = fairness.get("fslsm_deviation_flags", [])

    if fairness_flags or deviation_flags:
        with st.expander("View profile fairness details"):
            if fairness_flags:
                st.markdown("**Fairness Flags**")
                for flag in fairness_flags:
                    severity = flag.get("severity", "low")
                    icon = {"low": "\U0001f7e1", "medium": "\U0001f7e0", "high": "\U0001f534"}.get(severity, "\U0001f7e1")
                    st.markdown(
                        f"{icon} **{flag.get('field_name', 'Unknown')}** \u2014 "
                        f"*{flag.get('fairness_category', '')}* ({severity})\n\n"
                        f"  {flag.get('explanation', '')}\n\n"
                        f"  **Suggestion:** {flag.get('suggestion', '')}"
                    )

            if deviation_flags:
                st.markdown("**FSLSM Deviation Warnings**")
                for flag in deviation_flags:
                    st.markdown(
                        f"\u26a0\ufe0f **{flag.get('dimension', 'Unknown')}**: "
                        f"Persona baseline {flag.get('persona_value', '?')} \u2192 "
                        f"Profile value {flag.get('profile_value', '?')} "
                        f"(deviation: {flag.get('deviation', '?')})"
                    )


def render_learner_profile_info(goal):
    st.markdown("""
        <style>
        .section {
            background-color: #f8f9fa;
            padding: 15px;
            margin: 10px 0;
            border-radius: 8px;
        }
        .progress-indicator {
            color: #28a745;
            font-weight: bold;
        }
        .skill-in-progress {
            color: #ffc107;
        }
        .skill-required {
            color: #dc3545;
        }
        </style>
    """, unsafe_allow_html=True)
    learner_profile = goal["learner_profile"]
    with st.container(border=True):
        header_col, button_col = st.columns([4, 1])
        with header_col:
            st.markdown("#### 👤 Learner Information")
        with button_col:
            if st.button("Edit Profile", type="primary", key=f"open_edit_profile_{goal.get('id', 'current')}"):
                show_edit_profile_dialog(goal)
        st.write(learner_profile.get("learner_information", ""))

        st.markdown("#### 🎯 Learning Goal")
        st.write(learner_profile.get("learning_goal", ""))

    render_fairness_banners(goal)

    with st.container(border=True):
        render_cognitive_status(goal)
    with st.container(border=True):
        render_learning_preferences(goal)
    with st.container(border=True):
        render_behavioral_patterns(goal)


def render_cognitive_status(goal):
    learner_profile = goal["learner_profile"]
    # Cognitive Status
    st.markdown("#### 🧠 Cognitive Status")
    st.write("**Overall Progress:**")
    raw_progress = learner_profile["cognitive_status"]["overall_progress"]
    try:
        progress_val = float(raw_progress)
    except (TypeError, ValueError):
        progress_val = 0.0
    # st.progress requires float in [0.0, 1.0]; profiles store 0-100 percentages as floats.
    # Normalize any value > 1 (i.e. 0-100 range) down to 0.0-1.0.
    if progress_val > 1.0:
        progress_val = progress_val / 100.0
    progress_val = max(0.0, min(1.0, progress_val))
    st.progress(progress_val)
    st.markdown(f"<p class='progress-indicator'>{raw_progress}% completed</p>", unsafe_allow_html=True)
    render_skill_info(learner_profile)

def render_learning_preferences(goal):
    learner_profile = goal["learner_profile"]
    prefs = learner_profile.get('learning_preferences', {})
    st.markdown("#### 📚 Learning Preferences")

    # Display FSLSM dimensions
    st.write("**FSLSM Learning Style Dimensions:**")
    dims = prefs.get('fslsm_dimensions') or {}

    def _get_dim(d: dict, name: str, default: float = 0.0) -> float:
        """Accept either {"processing": x} or {"fslsm_processing": x}."""
        if name in d:
            v = d.get(name)
        else:
            v = d.get(f"fslsm_{name}")
        try:
            return float(v)
        except Exception:
            return float(default)

    processing = _get_dim(dims, "processing")
    perception = _get_dim(dims, "perception")
    inp = _get_dim(dims, "input")
    understanding = _get_dim(dims, "understanding")

    slider_specs = [
        ("Processing", "Active", "Reflective", processing),
        ("Perception", "Sensing", "Intuitive", perception),
        ("Input", "Visual", "Verbal", inp),
        ("Understanding", "Sequential", "Global", understanding),
    ]

    goal_id = goal.get("id", "current")
    for label, left_label, right_label, value in slider_specs:
        st.caption(f"{label}")
        col1, col2, col3 = st.columns([1, 3, 1])
        with col1:
            st.markdown(f"**{left_label}**")
        with col2:
            st.slider(
                label=label,
                min_value=-1.0,
                max_value=1.0,
                value=float(value),
                step=0.1,
                disabled=True,
                label_visibility="collapsed",
                key=f"view_fslsm_slider_{label.lower()}_{goal_id}",
            )
        with col3:
            st.markdown(f"**{right_label}**")

    fslsm_cfg = get_app_config()["fslsm_thresholds"]
    dim_values = {"perception": perception, "understanding": understanding, "processing": processing, "input": inp}

    def _describe(dim_name, value):
        t = fslsm_cfg[dim_name]
        if value <= t["low_threshold"]:
            return t["low_label"]
        elif value >= t["high_threshold"]:
            return t["high_label"]
        else:
            return t["neutral_label"]

    content_style = f"{_describe('perception', perception)}, {_describe('understanding', understanding)}"
    activity_type = f"{_describe('processing', processing)}, {_describe('input', inp)}"

    st.write(f"**Content Style:** {content_style}")
    st.write(f"**Preferred Activity Type:** {activity_type}")

    st.write("**Additional Notes:**")
    st.info(prefs.get('additional_notes', 'None'))

def render_behavioral_patterns(goal):
    goal_name = (goal.get("learner_profile", {}).get("goal_display_name", "") or goal.get("learning_goal", "Current Goal")) if isinstance(goal, dict) else "Current Goal"
    st.markdown(f"#### Behavioral Patterns — {goal_name}")

    # Fetch real metrics from backend
    user_id = st.session_state.get("userId")
    goal_id = None
    if isinstance(goal, dict) and "id" in goal:
        goal_id = goal["id"]
    bm_key = f"behavioral_metrics_{goal_id}"
    if bm_key not in st.session_state:
        st.session_state[bm_key] = get_behavioral_metrics(user_id, goal_id) if user_id else None
    metrics = st.session_state.get(bm_key)

    if metrics is None:
        # Fallback to LLM-generated text if endpoint unavailable
        learner_profile = goal["learner_profile"]
        bp = learner_profile.get("behavioral_patterns", {})
        st.write("**System Usage Frequency:**")
        st.info(bp.get("system_usage_frequency", "N/A"))
        st.write("**Session Duration and Engagement:**")
        st.info(bp.get("session_duration_engagement", "N/A"))
        st.write("**Motivational Triggers:**")
        st.info(bp.get("motivational_triggers", "N/A"))
        st.write("**Additional Notes:**")
        st.info(bp.get("additional_notes", "N/A"))
        return

    # --- Session Completion ---
    st.write("**Session Completion:**")
    total_in_path = metrics.get("total_sessions_in_path", 0)
    sessions_learned = metrics.get("sessions_learned", 0)
    if total_in_path > 0:
        st.progress(sessions_learned / total_in_path)
        st.caption(f"{sessions_learned} of {total_in_path} sessions completed")
    else:
        st.info("No learning path generated yet.")

    # --- Session Duration & Engagement ---
    st.write("**Session Duration & Engagement:**")
    sessions_completed = metrics.get("sessions_completed", 0)
    if sessions_completed > 0:
        avg_min = metrics.get("avg_session_duration_sec", 0) / 60.0
        total_min = metrics.get("total_learning_time_sec", 0) / 60.0
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Sessions Completed", sessions_completed)
        with col2:
            st.metric("Avg Duration", f"{avg_min:.1f} min")
        with col3:
            st.metric("Total Learning Time", f"{total_min:.1f} min")
    else:
        st.info("No completed sessions yet. Complete a learning session to see engagement metrics.")

    # --- Motivational Triggers ---
    st.write("**Motivational Triggers:**")
    trigger_count = metrics.get("motivational_triggers_count", 0)
    if sessions_completed > 0:
        st.caption(f"{trigger_count} motivational trigger(s) received across all sessions")
    else:
        st.info("No data yet.")

    # --- Mastery Progress ---
    st.write("**Mastery Progress:**")
    latest_mastery = metrics.get("latest_mastery_rate")
    mastery_history = metrics.get("mastery_history", [])
    if latest_mastery is not None:
        st.progress(min(float(latest_mastery), 1.0))
        st.caption(f"Latest mastery rate: {latest_mastery:.1%} (sampled {len(mastery_history)} time(s))")
    else:
        st.info("No mastery data yet. Study sessions to see your mastery trend.")


@st.dialog("Edit Profile")
def show_edit_profile_dialog(goal):
    learner_profile = goal.get("learner_profile", {})
    goal_id = st.session_state.get("selected_goal_id")
    user_id = st.session_state.get("userId")
    prefs = learner_profile.get("learning_preferences", {})
    dims = prefs.get("fslsm_dimensions") or {}

    def _get_dim(name: str, default: float = 0.0) -> float:
        value = dims.get(f"fslsm_{name}", dims.get(name, default))
        try:
            return float(value)
        except Exception:
            return float(default)

    mode = st.radio(
        "Choose update mode",
        ["Learning Preferences", "Learner Information"],
        key=f"edit_profile_mode_{goal_id}",
    )

    if mode == "Learning Preferences":
        st.caption("Adjust your current FSLSM dimensions directly using sliders.")
        slider_specs = [
            ("processing", "Processing", "Active", "Reflective"),
            ("perception", "Perception", "Sensing", "Intuitive"),
            ("input", "Input", "Visual", "Verbal"),
            ("understanding", "Understanding", "Sequential", "Global"),
        ]
        slider_values = {}
        for key_name, label, left_label, right_label in slider_specs:
            st.caption(label)
            col1, col2, col3 = st.columns([1, 3, 1])
            with col1:
                st.markdown(f"**{left_label}**")
            with col2:
                slider_values[key_name] = st.slider(
                    label=label,
                    min_value=-1.0,
                    max_value=1.0,
                    value=float(_get_dim(key_name)),
                    step=0.1,
                    label_visibility="collapsed",
                    key=f"edit_fslsm_slider_{key_name}_{goal_id}",
                )
            with col3:
                st.markdown(f"**{right_label}**")
        if st.button("Save FSLSM Changes", type="primary", key=f"save_fslsm_edit_{goal_id}"):
            learner_interactions = {
                "update_mode": "fslsm_slider_override",
                "slider_values": slider_values,
            }
            with st.spinner("Updating learning preferences..."):
                fresh_profile = get_learner_profile(user_id, goal_id)
                base_profile = fresh_profile if fresh_profile else learner_profile
                updated_profile = update_learning_preferences(
                    base_profile,
                    learner_interactions,
                    user_id=user_id,
                    goal_id=goal_id,
                )
            if updated_profile is None:
                st.error("Failed to update learning preferences. Please try again.")
                return
            goal["learner_profile"] = updated_profile
            propagate_profile_fields_to_other_goals(goal_id, sync_preferences=True)
            try:
                save_persistent_state()
            except Exception:
                pass
            st.toast("Learning preferences updated successfully.")
            st.rerun()
        return

    current_info = str(learner_profile.get("learner_information", "") or "")
    edited_info = st.text_area(
        "Learner Information",
        value=current_info,
        height=220,
        key=f"edit_learner_information_{goal_id}",
        help="You can edit your current learner information directly.",
    )
    pdf_file = st.file_uploader(
        "Upload resume to enrich learner information (PDF)",
        type="pdf",
        key=f"edit_resume_upload_{goal_id}",
    )
    if st.button("Save Learner Information Changes", type="primary", key=f"save_learner_info_{goal_id}"):
        resume_text = ""
        if pdf_file is not None:
            with st.spinner("Extracting text from resume..."):
                resume_text = extract_text_from_pdf(pdf_file)
        if not edited_info.strip() and not resume_text.strip():
            st.error("Provide edited learner information text or upload a resume before submitting.")
            return
        with st.spinner("Updating learner information..."):
            fresh_profile = get_learner_profile(user_id, goal_id)
            base_profile = fresh_profile if fresh_profile else learner_profile
            updated_profile = update_learner_information(
                base_profile,
                edited_learner_information=edited_info,
                resume_text=resume_text,
                user_id=user_id,
                goal_id=goal_id,
            )
        if updated_profile is None:
            st.error("Failed to update learner information. Please try again.")
            return
        goal["learner_profile"] = updated_profile
        propagate_profile_fields_to_other_goals(goal_id, sync_preferences=True)
        try:
            save_persistent_state()
        except Exception:
            pass
        st.toast("Learner information updated successfully.")
        st.rerun()


@st.dialog("Confirm Restart Onboarding")
def show_restart_onboarding_dialog():
    st.warning("All your progress will be cleared and you will be taken back to onboarding.")
    st.divider()
    col_confirm, _space, col_cancel = st.columns([1, 2, 0.7])
    with col_confirm:
        if st.button("Confirm", type="primary"):
            # Keep the user logged in after clearing progress
            user_id = st.session_state.get("userId", "default")
            backend_ep = st.session_state.get("backend_endpoint")
            prev_llm_type = st.session_state.get("llm_type")
            prev_available_models = st.session_state.get("available_models")
            try:
                st.session_state["_autosave_enabled"] = False
            except Exception:
                pass
            try:
                # Full reset: clear profiles/events/snapshots/state, not only UI state.
                if backend_ep:
                    status, _resp = delete_user_data(backend_ep, user_id)
                    if status != 200:
                        # Fallback for compatibility if /user-data is unavailable.
                        delete_persistent_state()
                else:
                    delete_persistent_state()
            except Exception:
                pass
            try:
                st.session_state.clear()
            except Exception:
                pass
            st.session_state["logged_in"] = True
            st.session_state["userId"] = user_id
            if backend_ep:
                st.session_state["backend_endpoint"] = backend_ep
            if isinstance(prev_available_models, list) and prev_available_models:
                st.session_state["available_models"] = prev_available_models
            if isinstance(prev_llm_type, str) and prev_llm_type.strip():
                st.session_state["llm_type"] = prev_llm_type
            try:
                st.switch_page("pages/onboarding.py")
            except Exception:
                st.rerun()
    with col_cancel:
        if st.button("Cancel"):
            try:
                st.rerun()
            except Exception:
                pass


@st.dialog("Confirm Delete Account")
def show_delete_account_dialog():
    st.error("This action is permanent. Your account and all associated data will be deleted and cannot be recovered.")
    st.divider()
    col_confirm, _space, col_cancel = st.columns([1, 2, 0.7])
    with col_confirm:
        if st.button("Delete", type="primary"):
            token = st.session_state.get("auth_token", "")
            if not token:
                st.error("No auth token found. Please log out and log back in, then try again.")
                return
            status, resp = auth_delete_user(token)
            if status == 200:
                try:
                    st.session_state.clear()
                except Exception:
                    pass
                st.session_state["logged_in"] = False
                st.session_state["userId"] = "default"
                st.success("Account deleted successfully.")
                try:
                    st.rerun()
                except Exception:
                    st.rerun()
            else:
                detail = resp.get("detail", "Unknown error") if isinstance(resp, dict) else str(resp)
                st.error(f"Failed to delete account: {detail}")
    with col_cancel:
        if st.button("Cancel"):
            try:
                st.rerun()
            except Exception:
                pass


render_learner_profile()

st.divider()
col_restart, col_delete = st.columns(2)
with col_restart:
    if st.button("Restart Onboarding", icon=":material/restart_alt:", help="Clear all progress and start onboarding from scratch (keeps a backup)"):
        show_restart_onboarding_dialog()
with col_delete:
    st.markdown("""
        <style>
        div[data-testid="stColumn"]:last-child button[kind="primary"] {
            background-color: #dc3545;
            border-color: #dc3545;
        }
        div[data-testid="stColumn"]:last-child button[kind="primary"]:hover {
            background-color: #bb2d3b;
            border-color: #b02a37;
        }
        </style>
    """, unsafe_allow_html=True)
    if st.button("Delete Account", icon=":material/delete_forever:", type="primary", help="Permanently delete your account and all associated data"):
        show_delete_account_dialog()
