from .goal_oriented_knowledge_explorer import goal_oriented_knowledge_explorer_system_prompt, goal_oriented_knowledge_explorer_task_prompt
from .search_enhanced_knowledge_drafter import search_enhanced_knowledge_drafter_system_prompt, search_enhanced_knowledge_drafter_task_prompt
from .learning_document_integrator import integrated_document_generator_system_prompt, integrated_document_generator_task_prompt
from .document_quiz_generator import document_quiz_generator_system_prompt, document_quiz_generator_task_prompt
from .content_bias_auditor import content_bias_auditor_system_prompt, content_bias_auditor_task_prompt
from .content_feedback_simulator import learner_feedback_simulator_system_prompt, learner_feedback_simulator_task_prompt_content
from .knowledge_draft_evaluator import knowledge_draft_evaluator_system_prompt, knowledge_draft_evaluator_task_prompt
from .integrated_document_evaluator import integrated_document_evaluator_system_prompt, integrated_document_evaluator_task_prompt
