from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Field, field_validator


class ChatbotBiasCategory(str, Enum):
    tone_bias = "tone_bias"
    language_bias = "language_bias"
    stereotype_bias = "stereotype_bias"
    cultural_assumption = "cultural_assumption"


class ChatbotBiasSeverity(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"


class ChatbotBiasFlag(BaseModel):
    message_index: int = Field(..., description="Index of the tutor message flagged (0-based).")
    bias_category: ChatbotBiasCategory
    severity: ChatbotBiasSeverity
    explanation: str = Field(..., description="Max 40 words explaining the detected bias.")
    suggestion: str = Field(..., description="Max 30 words suggesting how to fix the bias.")

    @field_validator("explanation")
    @classmethod
    def limit_explanation_words(cls, v: str) -> str:
        if len(v.split()) > 40:
            raise ValueError("Explanation must be 40 words or fewer.")
        return v

    @field_validator("suggestion")
    @classmethod
    def limit_suggestion_words(cls, v: str) -> str:
        if len(v.split()) > 30:
            raise ValueError("Suggestion must be 30 words or fewer.")
        return v


_DEFAULT_CHATBOT_ETHICAL_DISCLAIMER = (
    "This tutoring response was generated by an AI system. It may reflect biases present "
    "in its training data or prompt design. If you notice language that seems biased, "
    "condescending, or inappropriate, please report it so we can improve."
)


class ChatbotBiasAuditResult(BaseModel):
    bias_flags: List[ChatbotBiasFlag] = Field(default_factory=list)
    deterministic_flags: List[ChatbotBiasFlag] = Field(default_factory=list)
    overall_bias_risk: ChatbotBiasSeverity = ChatbotBiasSeverity.low
    audited_message_count: int = 0
    flagged_message_count: int = 0
    ethical_disclaimer: str = Field(default=_DEFAULT_CHATBOT_ETHICAL_DISCLAIMER)
